apiVersion: apps/v1
kind: Deployment
metadata: {name: postgres, labels: {app: postgres}}
spec:
  replicas: 1
  strategy: {type: Recreate}
  selector: {matchLabels: {app: postgres}}
  template:
    metadata: {labels: {app: postgres}}
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - {name: POSTGRES_DB, value: urumi}
            - {name: POSTGRES_USER, value: urumi}
            - {name: POSTGRES_PASSWORD, valueFrom: {secretKeyRef: {name: urumi-secrets, key: postgres-password}}}
            - {name: PGDATA, value: /var/lib/postgresql/data/pgdata}
          ports: [{containerPort: 5432}]
          readinessProbe: {exec: {command: ["pg_isready","-U","urumi"]}, periodSeconds: 10}
          livenessProbe: {exec: {command: ["pg_isready","-U","urumi"]}, initialDelaySeconds: 30, periodSeconds: 20}
          resources: {{ toYaml .Values.resources.db | nindent 12 }}
          volumeMounts: [{name: data, mountPath: /var/lib/postgresql/data}]
      volumes: [{name: data, persistentVolumeClaim: {claimName: postgres-data}}]
---
apiVersion: v1
kind: Service
metadata: {name: postgres}
spec: {selector: {app: postgres}, ports: [{port: 5432}]}
