FROM python:3.12-slim
RUN useradd -u 10001 -m app
WORKDIR /srv
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app ./app
USER 10001
EXPOSE 8000
CMD ["python","-m","app.main"]
